import "./globals.css";

export const metadata = {
    title: "todo-app",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <html>
                <head>
                    <link rel="icon" href="favicon-32x32.png"></link>
                    <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                    <link rel="preconnect" href="https://fonts.gstatic.com"></link>
                    <link
                        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap"
                        rel="stylesheet"
                    ></link>
                </head>
                <body className="bg-[#181824] font-josef">{children}</body>
            </html>
        </>
    );
}
